#!/usr/bin/env python3

import pathlib
import unittest


HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]


class ManagedConfigPreservationTests(unittest.TestCase):
    def test_cartographer_config_warns_and_installer_backs_up(self):
        config = (HERE / "cartographer.cfg").read_text(encoding="utf-8")
        installer = (HERE / "install.sh").read_text(encoding="utf-8")
        self.assertTrue(config.startswith("### WARNING: Do not edit this file"))
        backup = installer.index("cartographer.cfg.before-managed-update")
        overwrite = installer.index("cp ${SCRIPT_DIR}/cartographer.cfg")
        self.assertLess(backup, overwrite)

    def test_prime_tower_config_warns_and_installer_backs_up(self):
        feature = ROOT / "features" / "prime_tower"
        config = (feature / "prime_tower.cfg").read_text(encoding="utf-8")
        installer = (feature / "install.sh").read_text(encoding="utf-8")
        self.assertTrue(config.startswith("### WARNING: Do not edit this file"))
        backup = installer.index("${CUSTOM_CFG}.before-managed-update")
        overwrite = installer.index('cp -f "${SCRIPT_DIR}/prime_tower.cfg"')
        self.assertLess(backup, overwrite)


if __name__ == "__main__":
    unittest.main()
